[package]
name = "snake"
version = "0.1.0"
authors = ["Antti Lamminsalo <antti.lamminsalo@gmail.com>"]

[dependencies.cursive]
version = "0.6"
default-features = false
features = ["termion-backend"]

[dependencies]

